defaults:
  - feature: v1

workdir: ${env:PWD}
seed: 777

gcp:
  project_id:

lgbm:
  feature_cols: ${feature.feature_cols}
  cat_cols: ${feature.cat_cols}
  label_col: "Weekly_Sales"
  early_stopping_rounds: 200
  verbose_eval: 100
  params:
    num_iterations: 100000
    lambda_l1: 0.1
    lambda_l2: 0.1
    num_leaves: 32
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 1
    min_child_samples: 10
    task: train
    boosting_type: gbdt
    objective: rmse
    metric: mae
    max_depth: 4
    learning_rate: 0.1
    num_thread: -1
    max_bin: 256
    verbose: -1
    device: cpu
    scale_pos_weight: 1
    seed: ${seed}
ridge:
  feature_cols: ${feature.feature_cols}
  cat_cols: ${feature.cat_cols}
  label_col: "Weekly_Sales"

store:
  model_name: baseline
  save_path: ${workdir}/output/${store.model_name}
  model_path: ${workdir}/output/${store.model_name}/model
  log_path: ${workdir}/output/${store.model_name}/logs
  result_path: ${workdir}/output/${store.model_name}/result

hydra:
  run:
    dir: ${store.save_path}
